services:
  mysql:
    image: mysql:8.0
    container_name: spring_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sii_demo_db
      MYSQL_USER: sii_demo_user
      MYSQL_PASSWORD: sii_demo_pass
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
